### ISSUE TITLE
[MAJOR BUG] UTF-8 String error

### ISSUE THREAD

**Issue by tuanna222** [gameclosure/native-ios#34] opened 2015-02-02 11:55 UTC
UTF-8 strings can not display on native-ios:
~~~
new ui.TextView({
			superview: hintView,
			x: 0,
			y: 5,
			width: 270,
			height: 40,
			horizontalAlign: 'center',
			text: "BẮT CHỮ",
			fontFamily: FONT_FAMILY2,
			color: "#fdfdfd",
			size: 20,
			canHandleEvents: false
		});
~~~

**Comment by jwilm** [comment] 2015-02-02 17:14
What is `FONT_FAMILY2`? If your font doesn't have unicode symbols, it won't work.

**Comment by tuanna222** [comment] 2015-02-02 23:18
FONT_FAMILY2="Verdana"
It work with devkit v1 but not devkit v2. So I guess there are problems with texture manager.
Please help.

**Comment by jwilm** [comment] 2015-02-02 23:20
There was some updates to texture manager recently. It's possible that caused an issue. What version of devkit-core are you on?

**Comment by tuanna222** [comment] 2015-02-03 01:10
i use the lastest version [v2.1.1]

**Comment by jwilm** [comment] 2015-02-03 01:42
I haven't had a chance to repro this yet. Have you tried reverting back to 2.0.19?

**Comment by tuanna222** [comment] 2015-02-03 01:49
But it seems the iOS 64 bit was not supported at v2.0.19. So can not upload my app to apple store.

**Comment by jwilm** [comment] 2015-02-03 01:53
Is it a new app?

**Comment by tuanna222** [comment] 2015-02-03 01:55
Yes, it is

**Comment by jwilm** [comment] 2015-02-03 01:58
Would you mind checking that the issue is present or not in v2.0.19? Would help out a lot.

**Comment by tuanna222** [comment] 2015-02-03 02:28
I've tested with these versions and the versions which have error about UTF-8 strings is v2.1.0 and v2.1.1:
v2.0.19: working normally
v2.0.20: working normally
v2.1.0: UTF-8 string is not working
v2.1.1: UTF-8 string is not working
~~~
import ui.TextView as TextView;

exports = Class(GC.Application, function () {

  this.initUI = function () {
    var textview = new TextView({
      superview: this.view,
      text: "BẮT CHỮ",
      color: "white",
		fontFamily: "Verdana",
      x: 0,
      y: 100,
      width: this.view.style.width,
      height: 100
    });
  };

  this.launchUI = function () {};
});
~~~

**Comment by jwilm** [comment] 2015-02-03 02:32
Thanks for checking that out. I'll look into what broke in 2.1.0.

**Comment by jwilm** [comment] 2015-02-03 04:10
Should be fixed in devkit-core 2.1.2. Thanks for the help pinpointing when this was introduced.

From the iOS simulator:
![screen shot 2015-02-02 at 8 03 36 pm](https://cloud.githubusercontent.com/assets/4285147/6014378/6f51f3f2-ab17-11e4-86d7-b2fcfa8a8c30.png)

(added ascii to make sure something was rendering)

**Closed by jwilm** 2015-02-03 04:10 UTC

**Comment by tuanna222** [comment] 2015-02-03 05:32
I've tested ok on my app with v2.1.2. Thank Mr. Joe Wilm.

**Comment by jwilm** [comment] 2015-02-03 06:00
Glad to hear it works. Don't forget to let us know when your game is on the app store!
